### ISSUE TITLE
大佬,博客有空加个RSS订阅么

### ISSUE THREAD

**Issue by Kuri-su** [i6448038/i6448038.github.io#1]
:smile:

**Comment by i6448038** [comment]
行的，最近一周吧。可以关注我的公众号: 互联网技术窝 一般都是同步更新的😁


 
---原始邮件---
发件人: "Amatist_Kurisu"<notifications@github.com>
发送时间: 2019年5月23日(星期四) 晚上8:01
收件人: "i6448038/i6448038.github.io"<i6448038.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [i6448038/i6448038.github.io] 大佬,博客有空加个RSS订阅么 (#1)



😄

**Comment by Kuri-su** [comment]
好的 :laughing:

**Comment by woodyxiong** [comment]
同求rss

**Comment by i6448038** [comment]
@Kuri-su @woodyxiong 好的好的，最近加上。同时希望大家关注我的微信公众号：互联网技术窝

**Comment by woodyxiong** [comment]
> @Kuri-su @woodyxiong 好的好的，最近加上。同时希望大家关注我的微信公众号：互联网技术窝

好的好的，已关注

**Comment by i6448038** [comment]
@Kuri-su @woodyxiong RSS 已添加，看看能用不？

**Comment by Kuri-su** [comment]
> @Kuri-su @woodyxiong RSS 已添加，看看能用不？

OK, 可用

**Comment by woodyxiong** [comment]
> @Kuri-su @woodyxiong RSS 已添加，看看能用不？

可以了，谢啦！！！
