### ISSUE TITLE
贝壳这两年

### ISSUE THREAD

**Issue by i6448038** [i6448038/i6448038.github.io#2]
# 感受
老实讲，在贝壳的这两年工作上过的并不开心。
  "贝壳这家公司，骨子里还是个中介公司"。这是有过互联网工作经验的底层同事一致的看法。目前公司内部帮派林立、内斗严重。
  我们部门我们组的组织架构调整的实在是有点频繁，两年的时间，由龙哥到无领导状态再到刘XX，最后刘XX也走了，只剩下组长XXX挑大梁，挑了俩月不到，组长也撤了。我们组彻底属于无人管状态，虽说工作时间上自由了，但是最终导致我们组做的东西没人认可，没有领导晋升也困哪，绩效也不高。但是，除了我们组，其他组还是不错的，大家一派祥和。至于为什么这样，究其根本，是部门大boss没带过开发，所以开发只能从市场上找，而不能从嫡系群里直接拉过来的原因吧。
  凡事都有好的一面，在贝壳这两年，组内的小伙伴相处的还是很愉快的，我觉得是我目前工作中待过的最单纯、最和睦、最开心的工作组。当然咯，其他组什么情况我不算很清楚，至少我们组是这样的。
  抛开这些外在的事情，对于自身工作最大的转变我觉得是：我了解了什么是平台研发工程师，什么是业务研发工程师。

  以下是我这两年主要的工作内容，文档内容均为交接工作时候的总结，我觉得已经很详细了，所以没加改动，留个回忆吧。

# CMDB

## 概述

cmdb是自动化运维的基石，处于整个公司的最下游，为公司的整个上游提供服务。

目前CMDB的业务方主要是 IDC组和网络组同学，还有少有部分功能需要和SRE同学对接。

## 架构设计
设计方面，我们参照小米运维并结合贝壳当前情况，遵循KISS原则进行设计。<br/>
当前我们的cmdb和市面上开源的CMDB设计有很大区别：系统层面不提供对数据模型字段的增删改查接口。
这是有一定原因的：
1. 我们的MySQL不是自运维的，对MySQL表的使用必须遵循公司MySQL的使用规范，我们无法从程序层面对MySQL的表结构进行增删改查。
2. 我们没必要对MySQL的表结构进行增删改查：

     因为如果说能对表的结构进行增删改查，那么不就相当于在MySQL之上又实现了一个MySQL？

     再说业务其实并不关心你的表结构如何如何，哪些需要搜索，哪些字段需要加都是程序自己来决定的。有MySQL控制台就够了，为何还要花费大力气，再造一个控制台？
<br/>
 就目前CMDB的”兵来将挡水来土掩“，来一个业务新建一个模块，这是最好的选择！小米是这么做的，我们也是这么做的~

### 普通CMDB的数据存储架构：

![cp](https://user-images.githubusercontent.com/6186049/74085876-9310a180-4ab8-11ea-80e1-ca253b009a24.png)

所有数据粘在一张表中，容易创建数据模型，但是数据与数据之间的联系非常难建立：例如机器和交换机的关系、内存和机器的关系、机器和产品树的关系...

### 新CMDB的数据存储架构：
   
![new](https://user-images.githubusercontent.com/6186049/74085958-745eda80-4ab9-11ea-8eae-17fd1f004426.png)

设计上各个模块高度独立，这样会使模块之间耦合度低，易拆分，易聚合，易扩展。

## CMDB平台中的项目概况

<img width="1435" alt="dashbord" src="https://user-images.githubusercontent.com/6186049/74096164-13291c80-4b36-11ea-97e7-58e1e4cb135b.png">

CMDB现在整合了IDC组和网络组的工作平台，还提供了资源相关的接口。混合了一些项目内容，以下是项目清单和简单介绍：

### IDC资产管理
简述：
理论上CMDB上最重要的东西之一，机器资源的管理。围绕http server 展开，并无惊奇。

1. 服务器的录入、使用、下线等生命周期管理

2. 云主机的自动添加、更新和删除

3. 备件的录入、使用以及和实体机的关联

#### 简述：
在平台上不能够对腾讯云做增加和删除以及更新操作，能做的只是查看和修改管理员、自定义状态和标签等操作。

腾讯云是自动落DB的，无需手动更新。就是个定时脚本。

已知问题：腾讯云虚拟机在一分钟之内如果拉取次数超过某个值，腾讯云虚拟机就会被阻止拉取。

#### 简述:

对网络设备进行管理，包括查看、录入、修改等等。

#### 简述:

提供了给资源打标签的能力，无论是机器还是交换机，都可以打标签。标签是“key:xxxx”格式的

1、业务方标签普通使用

2、区分了业务方的机器，间接为监控报警提供了服

#### 简述

监控网络质量的，属于比较重要的项目。

和组内监控配合实现了此项目。

#### 架构图：

![pingmesh](https://user-images.githubusercontent.com/6186049/74086643-b854de00-4abf-11ea-966c-ec8ca0066dc8.png)

TOR和机器的关系，使用的是CMDB中存储的交换机和实体机的关联关系。

数据的采集，使用的是Prometheus提供的agent；

 对于监控数据的存储，主要依赖于监控同学。

前端渲染，页面使用 canvas 把节点都画出来，可以动态的扩展ping-mesh格子的大小

## 操作日志

会将交换机或者机器的修改记录记下来。

## 产品树节点挂载

![cps](https://user-images.githubusercontent.com/6186049/74086743-e129a300-4ac0-11ea-9dc2-9460d0eedf34.png)

将服务树的节点和资源挂载。

## 权限

网站管理登录权限，使用RBAC模型

**Comment by i6448038** [comment]
# 前端 

## CMDB为何要前后端分离？


前端现在发展的已经很成熟，从项目扩展性和易用性等角度考虑，使用单独的前端框架比自己使用 Html + jQ + UI库 方便太多了：

1、维护和扩展性方面更容易

2、代码书写更高效



## CMDB前端技术栈


使用的主要语言是 AngularJS 8.1.0

使用的语言是：typescript （语法非常简单，可以自行百度或者查看文档：https://www.tslang.cn/docs/home.html）

使用的前端框架是：在蚂蚁金服的Ant Design的angularJs版本ng-zerro之上再封装的框架，叫做：ng-alain （地址为：https://ng-alain.com/docs/getting-started/zh ）



## CMDB前端代码结构
前端接口乍一瞅感觉挺复杂的，例如下图：

![cmdb-fe1](https://user-images.githubusercontent.com/6186049/74087023-94939700-4ac3-11ea-9b5f-5de7f95369e7.png)

其实你只需要关注：

src目录下：app/routes 中的内容就好了

![cmdb-fe2](https://user-images.githubusercontent.com/6186049/74087029-a5440d00-4ac3-11ea-82ac-2701da422e9e.png)

其余的目录都可以不关心。

具体的目录什么意思，可以参考ng-alain的官方文档来查看：https://ng-alain.com/docs/scaffold/zh



## 开发说明：

### 画UI:

页面UI的集合，可以参照: 

+ Ant Design原生： https://ng.ant.design/docs/introduce/zh 
+ ng-alain官方demo: https://ng-alain.github.io/ng-alain/#/dashboard/v1
+ 对于官方demo，如果看上某个控件，可以直接去github上拷贝代码：https://github.com/ng-alain/ng-alain都在src目录下，巴拉巴拉就能找到源码，复制粘贴就完事儿。



ng-alain封装的各种表单、列表等等组件：https://ng-alain.com/components/view/zh

复制粘贴就够了，很简单。



## 简单指令：


https://ng-alain.com/docs/new-page/zh



新增一个模块(目录)：

ng g ng-alain:module xxxx



模块(例如模块是 sys)下新增一个页面：

ng g ng-alain:list log -m=sys


## 发布上线


1、本地安装angular环境，然后运行：ng build --prod

2、编译结束后，去./dist目录下找到编译好的文件

3、zip压缩成cmdb-fe.zip

4、将cmdb-fe.zip 发送至发布机器。

scp cmdb-fe.zip root@xxx.xxx.xxx.xxx:/home/sysop 

5、将cmdb-fe.zip 解压成 cmdb-fe

6、把 admin.dobox.ke.com.cp 删掉，把现有的 admin.dobox.ke.com 重命名为 admin.dobox.ke.com.cp

7、把 cmdb-fe 重命名为 admin.dobox.ke.com

8、发布推送指令：distrsync --access-token ROV6UVRJ1B4Z46B0PBEOBS4Y9U6N7P6IC2BXQ5J71MQ5PG86HV7PVDD2ZZH0SW0P --srcroot /home/sysop/admin.dobox.ke.com --module admin.dobox.ke.com

**Comment by i6448038** [comment]
# 后端
## 为什么俩项目？

![houduan_jiegou](https://user-images.githubusercontent.com/6186049/74087192-dffa7500-4ac4-11ea-9a43-603b0ac455fe.png)


最初的设想是将接口和管理后台所需的接口分两个项目分开，

接口是dobox那个项目(http://git.lianjia.com/liugang008/dobox)，

网站后台是cmdb那个项目(http://git.lianjia.com/liugang008/cmdb)，

但是，后来经过开发得知：网站越做越大，但是接口其实并不太多，而且网站的接口可以复用，于是后续打算将两个项目合二为一。



## 技术栈
开发语言：Go 1.12

cli框架：cobra  https://github.com/spf13/cobra

rpc框架：grpc https://www.grpc.io/docs/quickstart/go/    (少量使用，现在可以放弃)

http框架：echo https://echo.labstack.com/ 

包管理工具： Go mod

Excel: github.com/tealeg/xlsx

orm: gorm



## dobox项目结构


### dobox结构图


![dobox_mem_jiegou](https://user-images.githubusercontent.com/6186049/74087281-9eb69500-4ac5-11ea-8bba-6a5924646ea1.png)


全量接口需要返回数据库中的几乎所有数据，为了效率，添加了一个内存缓存，db会定时更新。

其他接口原本也打算直接复用内存中的数据，但是经过开发发现，有些场景对实时性还是有要求的，于是就直接访问了DB。



### 代码结构：


结合cobra的结构做的修改。



代码结构：

![dobox_code](https://user-images.githubusercontent.com/6186049/74087299-bbeb6380-4ac5-11ea-810a-87e6848323ae.png)




代码结构解释：

|目录|解释说明|
|---|---|
|bin|编译后的代码|
|cmd|保留cobra代码结构，入口|
|pkg|具体实现逻辑|
|pkg/basicres|DB和内存的更新|
|**pkg/control**|**具体的业务逻辑**|
|**pkg/control/pb**|**grpc的protobuf文件**|
|**pkg/control/service**|**对业务逻辑的封装复用**|
|**pkg/control/service2**|**对业务逻辑的封装复用的重构版，为完成**|
|**pkg/control/transport**|**grpc server和 http server的业务逻辑入口**|
|pkg/monitor|<font color='red'>可删除</font>|
|pkg/tag|<font color='red'>可删除</font>|
|**pkg/utils**|**数据库model、第三方接口、以及部分自己封装的工具代码**|
|script|<font color='red'>可删除</font>|
|vendor|go mod自带|



## cmdb项目结构


### 项目结构：

单纯的http server。少部分grpc残留，未来可修改

### 代码结构：
非常单纯，直接复用 cobra项目的结构。

![cmdb_code](https://user-images.githubusercontent.com/6186049/74087626-3ff31a80-4ac9-11ea-9321-63577b3bbe61.png)


|目录|解释说明|
|---|---|
|cmd|入口|
|**pkg**|**主要逻辑**|
|**pkg/grpc**|**grpc server**|
|**pkg/http**|**http server**|
|**pkg/utils**|**所需要的数据库model、第三方接口调用、自己封装的函数等**|
|vendor|go mod所带的|



## 代码发布


公司提供的指令式的发布方式，需要先自己编译打包，然后在将打包好的文件移动到代码发布机，然后再执行固定的发布指令。

非常繁琐，而且很容易出错误，于是我们用Jenkins自己扩展了自己的发布方式。

合并完代码后打tag，然后用Jenkins去git仓库拉相关的tag，然后编译，最后利用贝壳的推送指令推送。



## dobox代码发布


1、利用自身的 makefile 文件

2、从自己分支合并代码至 kecloud group 并打tag

3、利用 Jenkins 发布 

jenkins上的编写的发布脚本：
```
DOBOX_PATH=/usr/share/nginx/html/dobox/$tag

##发布机IP
PUBLIC_IP=10.33.107.20
PUBLIC_USERNAME=root
PUBLIC_PASSWORD=123qwe
PUBLIC_URL=http://10.26.27.146/dobox/$tag/dobox.tar.gz

##编译
export GOPROXY="http://artifactory.intra.ke.com/artifactory/api/go/go-virtual"
make
mkdir -p /var/lib/jenkins/workspace/dobox-online/bin

###构建发布文件
mkdir -p $DOBOX_PATH
cp bin/* $DOBOX_PATH
cd $DOBOX_PATH
mv control.config.toml config.toml
if [ -d "dobox" ];then
	rm -rf dobox/
fi
mkdir dobox
cd dobox
mkdir bin
mkdir conf
mkdir pid
cd ../
mv config.toml dobox/conf
mv control dobox/bin/
tar -cvzf dobox.tar.gz dobox/

##发布指令
sshpass -p $PUBLIC_PASSWORD ssh -o StrictHostKeyChecking=no $PUBLIC_USERNAME@$PUBLIC_IP "distrsync --access-token ROV6UVRJ1B4Z46B0PBEOBS4Y9U6N7P6IC2BXQ5J71MQ5PG86HV7PVDD2ZZH0SW0P --url $PUBLIC_URL --module dobox.ke.com"
```


## cmdb代码发布


1、目前是在liugang008项目上直接打包、打tag发布的，以后建议合并至kecloud分支上去

2、利用 Jenkins 发布 

Jenkins上的发布脚本：
```
CMDB_PATH=/usr/share/nginx/html/cmdb/$tag

##发布机IP
PUBLIC_IP=10.33.107.20
PUBLIC_USERNAME=root
PUBLIC_PASSWORD=123qwe
PUBLIC_URL=http://10.26.27.146/cmdb/$tag/cmdb.tar.gz

##编译
export GOPROXY=http://localhost:12000
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cmdb main.go


###构建发布文件
mkdir -p $CMDB_PATH
cp cmdb $CMDB_PATH
cp config.toml $CMDB_PATH
cp run.sh $CMDB_PATH
cd $CMDB_PATH
if [ -d "cmdb_online" ];then
	rm -rf cmdb_online/
fi
mkdir cmdb_online
cd cmdb_online
mkdir bin
mkdir conf
mkdir pid
cd ../
cp config.toml cmdb_online/conf
cp run.sh cmdb_online/bin/
cp cmdb cmdb_online/bin/
tar -cvzf cmdb.tar.gz cmdb_online/


##发布指令
sshpass -p $PUBLIC_PASSWORD ssh -o StrictHostKeyChecking=no $PUBLIC_USERNAME@$PUBLIC_IP "distrsync --access-token ROV6UVRJ1B4Z46B0PBEOBS4Y9U6N7P6IC2BXQ5J71MQ5PG86HV7PVDD2ZZH0SW0P --url $PUBLIC_URL --module api.cmdb.ke.com"
```



## 代码部署


现在要求一个域名：cmdb.intra.ke.com 下可以同时访问两个项目dobox和cmdb，如何做到的？



### 个人开发环境：



![nginx_conf](https://user-images.githubusercontent.com/6186049/74087958-0c65bf80-4acc-11ea-8547-b86188dace17.png)




### 线上开发环境：

![nginx_online1](https://user-images.githubusercontent.com/6186049/74087863-1c30d400-4acb-11ea-8f02-ba0fbc434db2.png)

![nginx_online2](https://user-images.githubusercontent.com/6186049/74087866-205cf180-4acb-11ea-974c-7f8ac62c03b6.png)

线上类似，也是做了代理






## 环境地址：


### 测试库：

#### DB :

host = "10.33.108.11"
port = "3306"
username = "root"
password = "homelink"
database = "cmdb" 和 “dobox_am”
charset = "utf8"



#### redis:

自建



### 线上库：

#### DB :

host = "m6900.zeus.mysql.ljnode.com"
port = "6900"
username = "dobox"
password = "kPpLJC5oxNXQxrq0"
database = "cmdb" 和 "dobox_am"



#### redis:

host = "m11056.zeus.redis.ljnode.com"
port = "11056"

**Comment by i6448038** [comment]
# 后端
## 为什么俩项目？

![houduan_jiegou](https://user-images.githubusercontent.com/6186049/74087192-dffa7500-4ac4-11ea-9a43-603b0ac455fe.png)


最初的设想是将接口和管理后台所需的接口分两个项目分开，

接口是dobox那个项目(http://git.lianjia.com/liugang008/dobox)，

网站后台是cmdb那个项目(http://git.lianjia.com/liugang008/cmdb)，

但是，后来经过开发得知：网站越做越大，但是接口其实并不太多，而且网站的接口可以复用，于是后续打算将两个项目合二为一。



## 技术栈
开发语言：Go 1.12

cli框架：cobra  https://github.com/spf13/cobra

rpc框架：grpc https://www.grpc.io/docs/quickstart/go/    (少量使用，现在可以放弃)

http框架：echo https://echo.labstack.com/ 

包管理工具： Go mod

Excel: github.com/tealeg/xlsx

orm: gorm



## dobox项目结构


### dobox结构图


![dobox_mem_jiegou](https://user-images.githubusercontent.com/6186049/74087281-9eb69500-4ac5-11ea-8bba-6a5924646ea1.png)


全量接口需要返回数据库中的几乎所有数据，为了效率，添加了一个内存缓存，db会定时更新。

其他接口原本也打算直接复用内存中的数据，但是经过开发发现，有些场景对实时性还是有要求的，于是就直接访问了DB。



### 代码结构：


结合cobra的结构做的修改。



代码结构：

![dobox_code](https://user-images.githubusercontent.com/6186049/74087299-bbeb6380-4ac5-11ea-810a-87e6848323ae.png)




代码结构解释：

|目录|解释说明|
|---|---|
|bin|编译后的代码|
|cmd|保留cobra代码结构，入口|
|pkg|具体实现逻辑|
|pkg/basicres|DB和内存的更新|
|**pkg/control**|**具体的业务逻辑**|
|**pkg/control/pb**|**grpc的protobuf文件**|
|**pkg/control/service**|**对业务逻辑的封装复用**|
|**pkg/control/service2**|**对业务逻辑的封装复用的重构版，为完成**|
|**pkg/control/transport**|**grpc server和 http server的业务逻辑入口**|
|pkg/monitor|<font color='red'>可删除</font>|
|pkg/tag|<font color='red'>可删除</font>|
|**pkg/utils**|**数据库model、第三方接口、以及部分自己封装的工具代码**|
|script|<font color='red'>可删除</font>|
|vendor|go mod自带|



## cmdb项目结构


### 项目结构：

单纯的http server。少部分grpc残留，未来可修改

### 代码结构：
非常单纯，直接复用 cobra项目的结构。

![cmdb_code](https://user-images.githubusercontent.com/6186049/74087626-3ff31a80-4ac9-11ea-9321-63577b3bbe61.png)


|目录|解释说明|
|---|---|
|cmd|入口|
|**pkg**|**主要逻辑**|
|**pkg/grpc**|**grpc server**|
|**pkg/http**|**http server**|
|**pkg/utils**|**所需要的数据库model、第三方接口调用、自己封装的函数等**|
|vendor|go mod所带的|



## 代码发布


公司提供的指令式的发布方式，需要先自己编译打包，然后在将打包好的文件移动到代码发布机，然后再执行固定的发布指令。

非常繁琐，而且很容易出错误，于是我们用Jenkins自己扩展了自己的发布方式。

合并完代码后打tag，然后用Jenkins去git仓库拉相关的tag，然后编译，最后利用贝壳的推送指令推送。



## dobox代码发布


1、利用自身的 makefile 文件

2、从自己分支合并代码至 kecloud group 并打tag

3、利用 Jenkins 发布 

jenkins上的编写的发布脚本：
```
DOBOX_PATH=/usr/share/nginx/html/dobox/$tag

##发布机IP
PUBLIC_IP=10.33.107.20
PUBLIC_USERNAME=root
PUBLIC_PASSWORD=123qwe
PUBLIC_URL=http://10.26.27.146/dobox/$tag/dobox.tar.gz

##编译
export GOPROXY="http://artifactory.intra.ke.com/artifactory/api/go/go-virtual"
make
mkdir -p /var/lib/jenkins/workspace/dobox-online/bin

###构建发布文件
mkdir -p $DOBOX_PATH
cp bin/* $DOBOX_PATH
cd $DOBOX_PATH
mv control.config.toml config.toml
if [ -d "dobox" ];then
	rm -rf dobox/
fi
mkdir dobox
cd dobox
mkdir bin
mkdir conf
mkdir pid
cd ../
mv config.toml dobox/conf
mv control dobox/bin/
tar -cvzf dobox.tar.gz dobox/

##发布指令
sshpass -p $PUBLIC_PASSWORD ssh -o StrictHostKeyChecking=no $PUBLIC_USERNAME@$PUBLIC_IP "distrsync --access-token ROV6UVRJ1B4Z46B0PBEOBS4Y9U6N7P6IC2BXQ5J71MQ5PG86HV7PVDD2ZZH0SW0P --url $PUBLIC_URL --module dobox.ke.com"
```


## cmdb代码发布


1、目前是在liugang008项目上直接打包、打tag发布的，以后建议合并至kecloud分支上去

2、利用 Jenkins 发布 

Jenkins上的发布脚本：
```
CMDB_PATH=/usr/share/nginx/html/cmdb/$tag

##发布机IP
PUBLIC_IP=10.33.107.20
PUBLIC_USERNAME=root
PUBLIC_PASSWORD=123qwe
PUBLIC_URL=http://10.26.27.146/cmdb/$tag/cmdb.tar.gz

##编译
export GOPROXY=http://localhost:12000
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cmdb main.go


###构建发布文件
mkdir -p $CMDB_PATH
cp cmdb $CMDB_PATH
cp config.toml $CMDB_PATH
cp run.sh $CMDB_PATH
cd $CMDB_PATH
if [ -d "cmdb_online" ];then
	rm -rf cmdb_online/
fi
mkdir cmdb_online
cd cmdb_online
mkdir bin
mkdir conf
mkdir pid
cd ../
cp config.toml cmdb_online/conf
cp run.sh cmdb_online/bin/
cp cmdb cmdb_online/bin/
tar -cvzf cmdb.tar.gz cmdb_online/


##发布指令
sshpass -p $PUBLIC_PASSWORD ssh -o StrictHostKeyChecking=no $PUBLIC_USERNAME@$PUBLIC_IP "distrsync --access-token ROV6UVRJ1B4Z46B0PBEOBS4Y9U6N7P6IC2BXQ5J71MQ5PG86HV7PVDD2ZZH0SW0P --url $PUBLIC_URL --module api.cmdb.ke.com"
```



## 代码部署


现在要求一个域名：cmdb.intra.ke.com 下可以同时访问两个项目dobox和cmdb，如何做到的？



### 个人开发环境：



![nginx_conf](https://user-images.githubusercontent.com/6186049/74087958-0c65bf80-4acc-11ea-8547-b86188dace17.png)




### 线上开发环境：

![nginx_online1](https://user-images.githubusercontent.com/6186049/74087863-1c30d400-4acb-11ea-8f02-ba0fbc434db2.png)

![nginx_online2](https://user-images.githubusercontent.com/6186049/74087866-205cf180-4acb-11ea-974c-7f8ac62c03b6.png)

线上类似，也是做了代理






## 环境地址：


### 测试库：

#### DB :

host = "10.33.108.11"
port = "3306"
username = "root"
password = "homelink"
database = "cmdb" 和 “dobox_am”
charset = "utf8"



#### redis:

自建



### 线上库：

#### DB :

host = "m6900.zeus.mysql.ljnode.com"
port = "6900"
username = "dobox"
password = "kPpLJC5oxNXQxrq0"
database = "cmdb" 和 "dobox_am"



#### redis:

host = "m11056.zeus.redis.ljnode.com"
port = "11056"

**Comment by i6448038** [comment]
# 数据库

## cmdb



## dobox_am

**Comment by i6448038** [comment]
# pingmesh

## 目的

+ 定位业务的延迟是否因为网络问题
+ 提供并且跟踪当前网络服务水平（SLA）
+ 监控告警、故障定位

## 整体架构图


![pingmesh](https://user-images.githubusercontent.com/6186049/74096449-440b5080-4b3a-11ea-88fd-2576977c09ab.png)



这属于组内合作的产物：

1、TOR和机器的关系，使用的是CMDB中存储的交换机和实体机的关联关系。

2、数据的采集，使用的是Prometheus提供的agent；对于监控数据的存储，主要依赖于监控同学的M3DB。

#  详细过程

## Prometheus agent(blackbox_exporter)的部署和改进

prometheus的agent就是一个http server，每次Prometheus会向agent发请求，然后把响应数据存进m3db。

访问方式：http://10.200.1.241:1920/probe?module=icmp&target=10.200.18.88



### 部署

第一批机器是我们发邮件告诉业务方，让业务方来安装agent部署的。

目前agent已经打成了yum包，可以使用ansible 来批量部署。

后续打算和IDC同学商量，在新机器初始化的时候，就会将agent作为基础组件，直接安装至机器，无需再而外安装。



### agent改进

原有agent没有限速，为了防止恶意访问，我们增加了限速功能。

目前的agent已经经过改良，10秒钟内最多访问 600次，如果超过次数，将访问受限制，直至10秒钟之后才可以继续访问


##  ping-mesh主页展示



<img width="1436" alt="ping_main" src="https://user-images.githubusercontent.com/6186049/74097004-97cd6800-4b41-11ea-9169-8eeabb5c83cd.png">

通过图形形象的展现出当前网络的情况。

基本逻辑，通过CMDB中保存的IP，从Prometheus 中拉取数据，然后展现给页面。



## 当前网络情况


基本逻辑图：



![ping_main_coding](https://user-images.githubusercontent.com/6186049/74097090-ed564480-4b42-11ea-8f5f-a5d9c2b27223.png)


### 如何获取Prometheus中的数据？


#### 向监控同学注册job。目前是发邮件
     获取所得job和token是：

     job: pingmesh

     token: c49fcrcOU


#### 根据现有已经注册的IP，获取监控数据。
为保证呈现的网格数据是有序的，获取IP的时候要根据TOR进行排序。



Prometheus提供的接口：

1、目前使用的是：

http://api.insight.intra.ke.com/data/api/v1/query_range?query=up{job="pingmesh", from="xxx.xxx.xxx.xx"}&start=xxxx&end=xxxx&step=60s



#### 获取数据现在有限制1万条的解决办法


数据现在有限制一万条，假如部署了600个节点，那么就有 600 X 600 = 360000 条数据。

如何获取数据？目前我们的解决方案，是注册监控任务的时候，会标记 "from" 哪个IP "to" 哪个IP，那么如果我想获取某个IP A到另外所有节点的数据，我只需拿到“from” A的数据就行了。

然后把不同的IP 并发的从Prometheus中获取，最多600个并发请求，曾仔细询问过监控同学，对监控影响不大。



### 前端如何展现？
假如都是写html，一个div是一个网格，那么最多将有360000个div标签，前端页面将直接卡死。

目前我们采用的是画图的方式，只用一个 canvas 标签，然后用js在canvas上画“方块”。

固定好canvas的长度和宽度(长度和宽度是相等的，因为是正方形)，然后根据长度和格子的数量等比例的缩放。



#### 牵扯的表结构

|表名|说明|
|---|---|
|pingmesh_ips|当前注册进pingmesh的IP|


## 历史网络质量


Prometheus中最多可以存半年的数据，所以我们尽量提供一个整体的历史数据表格。



### 如何知道xx时间点记录了哪些IP？

我们目前使用了一张表“pingmesh_ips”，这张表只增不减也不更新。

这张表除了记录IP还记录下了时间戳，这就相当于一个IP的更新历史，这样你给我一个时间点，我就可以根据这张表的时间戳来判断当时这个时间点的IP是什么。



**牵扯的表结构**

|表名|说明|
|---|---|
|pingmesh_ips|当前注册进pingmesh的IP|


### 如何知道xx时间点的错误信息？


我们后台运行了一个定时脚本，由于Prometheus是整点每10s采集数据的，所以，我们只需要后台运行一个脚本，每隔一个时间段运行一次，如果有错误，则记录下错误信息，就OK了



**牵扯的表结构**

|表名|说明|
|---|---|
|pingmesh_history_errors|当前注册进pingmesh的IP|




## 网络节点历史数据


我们不仅需要知道某个时间点整体的网络情况，还需要知道，某时刻点对点的网络情况。

这个我们配置了Grafana，然后用iframe嵌了图。

地址为：

http://d.insight.intra.ke.com/d/pf8jKOTZz/ping?orgId=1&var-from=10.200.18.212&var-target=10.200.16.146&from=now-1h&to=now





## 节点配置

### 现有机房TOR列表

![node_conf](https://user-images.githubusercontent.com/6186049/74096791-67d09580-4b3e-11ea-84b2-a6d3ed070707.png)


### 机器监控绑定和解绑


首先把IP记录在CMDB中，然后在调用接口更新普罗米修斯的数据



**注册：**
curl -d '{"url":"http://blackbox.insight.intra.ke.com/probe?module=icmp&target=10.200.20.234:8720","limit":1000,"interval":60,"job":"pingmesh","token":"xxxxx","tags":{"monitor_type":"icmp","from":"xxxx" ,"source_tor":"xxx","to_tor":"xxxx","target":"10.200.20.234"}}' api.monitor.ke.com/kernel/register/task



注意，主要是url要写对

**解绑：**
curl -d '{"url":"http://blackbox.insight.intra.ke.com/probe?module=icmp&target=10.200.20.234:8720","job":"pingmesh","token":"xxxxx"}' api.monitor.ke.com/kernel/cancel/task



**CMDB中相对应的表**
|表名|说明|
|---|---|
|pingmesh_ips|已注册的ip|


## 自定义TOR列表


非常简单，单表操作。但是查询的pingemsh数据的时候，需要把此张表中的自定义TOR加上



**表结构**

|表名|说明|
|---|---|
|pingmesh_custom_tors|自定义TOR|
|pingmesh_custom_tor_ip_mappings|自定义TOR和IP的关系|

**Comment by i6448038** [comment]
# 部分接口

## SRE修改管理员

本接口暂时仅为了SRE同学提供。认证方式已为SRE同学提供。
|API|说明|
|---|---|
|url|http://cmdb.intra.ke.com/api/instance/administrator/modify|
|method|post|
|header|Content-Type:application/json <br/>token:xxxxxxxxx<br/>md5(role + signature + sn + 时间戳)<br/>role:xxxxx<br/>|
|请求参数：|{<br/>"sn":"xxx",<br/>"administrator":"xxx",<br/>"tree_id":"xxx"<br/>}|
|请求说明：|注意：<br/>1、参数“sn”为必传参数。<br/>2、“administrator”和"tree_id"两个参数必选其一，不能同时为空。<br/>3、如果"administrator"为空，则说明只修改机器的产品树节点<br/>4、如果"tree_id"为空，则说明只修改机器的管理员<br/>5、关于产品树与机器解绑的情况，不在此接口的作用范围内。所以，若参数tree_id为零或空，则证明是修改机器的管理员，而不修改产品树节点<br>|
|响应：|响应的类型完全遵循http响应值的意思（http status 为 200代表成功，400代表请求错误....）<br/><br/>如果成功：<br/>{xxxxxxx},<br/> <br/>如果失败：<br/>{"xxxxx"}|

## 腾讯云自动添加管理员

![tx_cloud_auto](https://user-images.githubusercontent.com/6186049/74126826-e4817380-4c13-11ea-8943-23f4bbafc6bb.png)

**Comment by GeminiBalaBala** [comment]
刚哥威武,互联网大牛刚,贝壳果然是个大坑
